### ISSUE TITLE
Help with window overlay

### ISSUE THREAD

**Issue by purpl3F0x** [rafzi/hacklib#3]
Hello, I have an opengl game that i want to put an overlay on, I'm trying the following but it doesn't seem to do something when I load the module (it seems to get loaded correctly). Am i doing something wrong ?

```cpp
#include "hacklib/Main.h"
#include "hacklib/ConsoleEx.h"
#include "hacklib/D3DDeviceFetcher.h"
#include "hacklib/Hooker.h"
#include <cstdio>


#include "hacklib/DrawerD3D.h"
#include "hacklib/DrawerOpenGL.h"
#include "hacklib/WindowOverlay.h"


hl::StaticInit<class MyMain> g_main;
const hl::IHook *g_indexedHook;


class MyMain : public hl::Main
{
private:
    hl::WindowOverlay overlay;
#ifdef _WIN32
    hl::DrawerD3D drawer;
#else
    hl::DrawerOpenGL drawer;
#endif
public:
    bool init() override
    {
        if (overlay.create() != hl::WindowOverlay::Error::Okay)
        {
            hl::MsgBox("Error", "Could not create overlay");
            return false;
        }

        overlay.registerResetHandlers([&] { drawer.onLostDevice(); }, [&] { drawer.onResetDevice(); });
        overlay.setTargetRefreshRate(100);
        drawer.setContext(overlay.getContext());


        return true;
    }

    bool step() override
    {
        if (GetAsyncKeyState(VK_HOME) < 0)
            return false;

        overlay.beginDraw();
        drawer.drawCircle(100, 100, 50, hl::Color(100, 255, 100, 50));
        overlay.swapBuffers();

        return true;
    }

    hl::Hooker m_hooker;
    hl::ConsoleEx m_con;
};
```

**Comment by rafzi** [comment]
Hi and thanks for your interest!

Your usage looks good to me. I'd first verify that WindowOverlay::GetTargetWindow does correctly select the window that you expect to track for your target application. This window needs to be the foreground (active) window for the overlay to be displayed.

Also note that it cannot be used when the game is in exclusive fullscreen mode, because the overlay is a separate window. So you need to use windowed or borderless window mode.

**Comment by purpl3F0x** [comment]
You were correct, the circle was just very thin and transparent and didn't saw it, (maybe change it to filled circle with a solid color on the docs?).
Yes fullscreen is an issue... I wonder how those fps and alike programs do it 🤔
